# This file is automatically generated. Do not edit.

def style(str)
  PixateFreestyle.initializePixateFreestyle
  PixateFreestyle.styleSheetFromSource(str, withOrigin:0)
  PixateFreestyle.updateStylesForAllViews
end
