# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'
require 'rubygems'
require 'motion-pixate'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'HelloWorld'
  app.pixate.key  = 'KEY CODE'
  app.pixate.user = 'USER ID'
  app.pixate.framework = 'vendor/PXEngine.framework'
end
